name: flutter_portfolio
description: Ömral Cörüt Personal Website.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.4.0-nullsafety.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.0.0-nullsafety
  url_launcher: ^6.0.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto_Slab
      fonts:
        - asset: fonts/Roboto_Slab/RobotoSlab-Light.ttf
          weight: 300
        - asset: fonts/Roboto_Slab/RobotoSlab-Regular.ttf
          weight: 400
        - asset: fonts/Roboto_Slab/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/Roboto_Slab/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/Roboto_Slab/RobotoSlab-Bold.ttf
          weight: 700
  assets:
    - images/